#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

CURRENT_SYSTEM="$(uname -s)"

export NH_SHOW_ACTIVATION_LOGS=1

if [ "$CURRENT_SYSTEM" = "Darwin" ]; then
    exec nh darwin switch path:.
elif [ "$CURRENT_SYSTEM" = "Linux" ]; then
    if [ -f "/etc/NIXOS" ]; then
        exec nh os switch path:.
    else
        exec nh home switch path:.
    fi
else
    echo "Unsupported system: $CURRENT_SYSTEM"
    exit 1
fi
